# Generated by Django 4.2 on 2024-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_iv2gcq', upload_to='image'),
        ),
    ]
