# Generated by Django 4.2 on 2024-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_video_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
