# Generated by Django 4.2 on 2024-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='files',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
