# Generated by Django 4.2 on 2024-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='files',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
