# Generated by Django 4.2 on 2024-07-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
