# Generated by Django 4.2 on 2024-07-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DARK-SOULS-1', 'Darksouls1'), ('DARK-SOULS-2', 'Darksouls2'), ('DARK-SOULS-3', 'Darksouls3'), ('ELDEN-RING', 'Eldenring'), ('DEMONS-SOULS', 'Demonssouls'), ('BLOOD-BORNE', 'Bloodborne'), ('SEKIRO-SHADOWS-DIE-TWICE', 'Sekiroshadowsdietwice')], max_length=24)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
