# Generated by Django 4.2 on 2024-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_iv2gcq', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='default-game', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
