# Generated by Django 4.2 on 2024-07-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trending',
        ),
    ]
